Repository IATI/IATI-Guidance, pull requests merged in 2018-02, with the labels that each got.

#299 2.03 changelog tweaks
  en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
Labels: Knowledge Base, complete

#294 Decimal upgrade to 2.03- changelog
  en/upgrades/all-versions.rst
  en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
Labels: Knowledge Base, complete

#300 Fix diff link in 2.01 changelog
  en/upgrades/integer-upgrade-to-2-01/2-01-changes.rst
Labels: bug, complete

#302 Format Codelists in 2.03 Changelog
  en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
Labels: complete, proof read

#303 Update decimal-upgrade-to-2-03.rst
  en/upgrades/decimal-upgrade-to-2-03.rst
Labels: bug, complete

#304 Fix Codelist name capitalisation
  en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
Labels: complete, proof read

#307 Add 2.03 page links
  en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
Labels: proof read

#306 Fix copypaste error in 2.02 Upgrade info.
  en/upgrades/decimal-upgrade-to-2-02.rst
Labels: complete, proof read

#301 Merge master into live
  en/datastore/reference/data-api.rst
  en/upgrades/all-versions.rst
  en/upgrades/decimal-upgrade-to-2-02.rst
  en/upgrades/decimal-upgrade-to-2-03.rst
  en/upgrades/decimal-upgrade-to-2-03/2-03-changes.rst
  en/upgrades/integer-upgrade-to-2-01/2-01-changes.rst
Labels: complete
